"""add match live-timing columns

Revision ID: 9ee2761f45b6
Revises: 0c4b59d7dfca
Create Date: 2026-09-12 10:22:00.664252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tournament_server.db


# revision identifiers, used by Alembic.
revision: str = '9ee2761f45b6'
down_revision: Union[str, None] = '0c4b59d7dfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('phase', sa.String(length=20), nullable=False))
    op.add_column('matches', sa.Column('phase_deadline', tournament_server.db.UTCDateTime(), nullable=True))
    op.add_column('matches', sa.Column('paused', sa.Boolean(), nullable=False))
    op.add_column('matches', sa.Column('remaining_seconds_at_pause', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'remaining_seconds_at_pause')
    op.drop_column('matches', 'paused')
    op.drop_column('matches', 'phase_deadline')
    op.drop_column('matches', 'phase')
    # ### end Alembic commands ###
