"""add match live-timing columns

Revision ID: 9ee2761f45b6
Revises: 0c4b59d7dfca
Create Date: 2026-09-12 10:22:00.664252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import tournament_server.db


# revision identifiers, used by Alembic.
revision: str = '9ee2761f45b6'
down_revision: Union[str, None] = '0c4b59d7dfca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `phase` and `paused` are NOT NULL, so adding them to a `matches`
    # table that may already have rows (any pre-existing self-hosted
    # install) requires a `server_default` -- SQLite refuses `ALTER TABLE
    # ... ADD COLUMN ... NOT NULL` with no default otherwise. The
    # server_default is left in place afterward rather than dropped: on
    # SQLite, dropping it requires `batch_alter_table` (copy-and-recreate
    # the whole table), which is more risk than it's worth here -- the
    # model's Python-side `default=` already governs every row inserted
    # through the ORM going forward regardless of what the column's DDL
    # default says, so a lingering server_default is harmless.
    op.add_column(
        'matches',
        sa.Column(
            'phase', sa.String(length=20), nullable=False,
            server_default='not_started',
        ),
    )
    op.add_column('matches', sa.Column('phase_deadline', tournament_server.db.UTCDateTime(), nullable=True))
    op.add_column(
        'matches',
        sa.Column('paused', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('matches', sa.Column('remaining_seconds_at_pause', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'remaining_seconds_at_pause')
    op.drop_column('matches', 'paused')
    op.drop_column('matches', 'phase_deadline')
    op.drop_column('matches', 'phase')
    # ### end Alembic commands ###
